### ISSUE TITLE
Questions about what the code does.

### ISSUE THREAD

**Issue by Joeclinton1** [alyssarosenzweig/scratch-llvm#9]
Hello, 

I have forked the github project and want to improve the code but there is a lot there and it's difficult to figure out how it works. Do you think you could explain in detail the code, especially backend.js and IR.js, so i could know what's happening here.

I want to remake the way the script runs so that instead of doing all this putchar, putnum and stacks stuff, it just adds the closest scratch equivalent of the input functions. Is this possible to do and what parts do I need to change to make this happen. I'd prefer to modify your project rather than starting from scratch as you've already done a considerable amount of the work.

Edit: Actually, perhaps I don't need an llvm if my aim isn't to convert to machine code but is to simply parse c and convert to scratch json, it might be better to keep the natural human readable code.

**Comment by alyssarosenzweig** [comment]
Given the code is 5 years old now...

>    Do you think you could explain in detail the code, especially
>    backend.js and IR.js, so i could know what's happening here.

Yeah, your guess is about as good as mine.

**Comment by Joeclinton1** [comment]
@alyssarosenzweig Thanks, I guess I'll just go with making a translator rather than using llvm.
